### ISSUE TITLE
Add export of other Policy Type

### ISSUE THREAD

**Issue by jbperrin88** [scottdware/panco#1]
Hi there,

First of all ... Whaou !! thank you . Nice soft ! 

I'm so happy with it.

Can you please add export (maybe import too) of other policy Type (Policy based forwarding , nat ...)

Regards !

**Comment by scottdware** [comment]
Thank you, @jbperrin88, I appreciate it!

So, last week, I actually just finalized importing and exporting NAT rules. I haven't built the new binaries yet, but should have them ready by later today/first thing tomorrow morning.

As for the other policy types, I will work on that. I wanted to make sure I got the main security rules and NAT rules as they are the most heavily used.

**Comment by scottdware** [comment]
The new version and binaries are available for download - https://github.com/scottdware/panco/releases/tag/v2020.02-1

**Comment by scottdware** [comment]
Just a quick update, in the next couple of weeks, I'll be releasing a new version which allows policy actions on security, NAT, and PBF.

**Comment by scottdware** [comment]
New June release is up. This allows you to import/export Security, NAT or Policy-Based Forwarding rules, along with a few other good changes!

https://panco.dev
