### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by Area51Brett** [scottdware/panco#3]
Getting a bunch of errors when running this but I'm not sure what I'm missing.
![image](https://user-images.githubusercontent.com/4419657/138503169-4ca4c7c4-2064-4d46-ae4e-e00102332938.png)

**Comment by scottdware** [comment]
Hi @Area51Brett 

Can you share with me the CSV file you’re using?

**Comment by iRobotSA** [comment]
Hi, I am getting the same issue. Would you be able to assist?
And thank you for this cool app

**Comment by iRobotSA** [comment]
Found the issue is the CSV export that puts ";" instead of the comma. Edited it in Notepad++ to replace the the ":" with a comma and save.
